### ISSUE TITLE
Team leader needs to review documentation and check for uniformity

### ISSUE THREAD

**Issue by clj500** [lgist2/group2#4]

**Comment by lgist2** [comment]
@clj500, @rlb32 , @rlb32  -> I have finished section 3 about system features. I only added 3 System features because some of the "features" we are to add correlate with being a sub-feature of the main ones. For example, "Create Account" would be a main feature and a sub feature for that would be "Edit account after creation". Take a look at it and let me know what else I should add if needed or if there are changes we need to discuss.
Also, we are still missing section 1 and I'm still looking over some things on our SRS, so I will get back with you all once I have read through everything. Thank you.

**Comment by clj500** [comment]
Looks like Section 1 has been completed. Levi, you can go ahead and review the SRS document and check for uniformity. I am also reviewing the SRS document right now to make sure we didn't miss anything. There are still a few sections missing in regard to references but currently I don't think we have any references so we can probably just clarify that under those sections.
